version: 2.1
orbs:
  node: circleci/node@7.1.0
  codecov: codecov/codecov@4.2.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/gofinances-web/node_modules
      - run: npm run test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
    test:
      jobs:
        - test
